In [14]:
import pandas as pd
import numpy as np
d1={'id':[101,102,103,104,105],
    'fname':['eran','isgar','falton','yonah','esha'],
    'lname':['pling','hoon','kiljah','toorbani','kling'],
    'age':[22,34,33,16,29]}
d2={'prof':['eko','dr','engg','pipe','coder'],
    'id':[103,104,105,106,107],
    'loc':['sonpur','cairo','afg','egypt','morocco'],
    'sal':[20000,12000,44000,28000,60000]}
d1

{'id': [101, 102, 103, 104, 105],
 'fname': ['eran', 'isgar', 'falton', 'yonah', 'esha'],
 'lname': ['pling', 'hoon', 'kiljah', 'toorbani', 'kling'],
 'age': [22, 34, 33, 16, 29]}

In [15]:
d2

{'prof': ['eko', 'dr', 'engg', 'pipe', 'coder'],
 'id': [103, 104, 105, 106, 107],
 'loc': ['sonpur', 'cairo', 'afg', 'egypt', 'morocco'],
 'sal': [20000, 12000, 44000, 28000, 60000]}

In [16]:
df1=pd.DataFrame(d1)
df1

    id   fname     lname  age
0  101    eran     pling   22
1  102   isgar      hoon   34
2  103  falton    kiljah   33
3  104   yonah  toorbani   16
4  105    esha     kling   29

In [17]:
df2=pd.DataFrame(d2)
df2

    prof   id      loc    sal
0    eko  103   sonpur  20000
1     dr  104    cairo  12000
2   engg  105      afg  44000
3   pipe  106    egypt  28000
4  coder  107  morocco  60000

In [23]:
df3=pd.merge(df1,df2,on='id',how='inner')[['fname','lname']]
df3

    fname     lname
0  falton    kiljah
1   yonah  toorbani
2    esha     kling

In [25]:
df4=pd.merge(df1,df2,how='left')
df4

    id   fname     lname  age  prof     loc      sal
0  101    eran     pling   22   NaN     NaN      NaN
1  102   isgar      hoon   34   NaN     NaN      NaN
2  103  falton    kiljah   33   eko  sonpur  20000.0
3  104   yonah  toorbani   16    dr   cairo  12000.0
4  105    esha     kling   29  engg     afg  44000.0

In [26]:
df4=pd.merge(df1,df2,how='right')
df4

    id   fname     lname   age   prof      loc    sal
0  103  falton    kiljah  33.0    eko   sonpur  20000
1  104   yonah  toorbani  16.0     dr    cairo  12000
2  105    esha     kling  29.0   engg      afg  44000
3  106     NaN       NaN   NaN   pipe    egypt  28000
4  107     NaN       NaN   NaN  coder  morocco  60000

In [27]:
df4=pd.merge(df1,df2,how='outer')
df4

    id   fname     lname   age   prof      loc      sal
0  101    eran     pling  22.0    NaN      NaN      NaN
1  102   isgar      hoon  34.0    NaN      NaN      NaN
2  103  falton    kiljah  33.0    eko   sonpur  20000.0
3  104   yonah  toorbani  16.0     dr    cairo  12000.0
4  105    esha     kling  29.0   engg      afg  44000.0
5  106     NaN       NaN   NaN   pipe    egypt  28000.0
6  107     NaN       NaN   NaN  coder  morocco  60000.0

In [28]:
df4.isna().sum()

id       0
fname    2
lname    2
age      2
prof     2
loc      2
sal      2
dtype: int64