In [1]:
import numpy as np
import pandas as pd

In [2]:
# Inputs Features
outlook = ['Sunny', 'Sunny', 'Overcast', 'Rain', 'Rain', 'Rain', 'Overcast', 'Sunny', 'Sunny', 'Rain', 'Sunny', 'Overcast', 'Overcast', 'Rain']
temp = ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild']
humidity = ['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'High']
windy = ['False', 'True', 'False', 'False', 'False', 'True', 'True', 'False', 'False', 'False', 'True', 'True', 'False', 'True']
# Output Labels
play = ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes','Yes', 'Yes', 'No']

In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import MultinomialNB

In [8]:
zipdata=list(zip(outlook,temp,humidity,windy))
zipdata

[('Sunny', 'Hot', 'High', 'False'),
 ('Sunny', 'Hot', 'High', 'True'),
 ('Overcast', 'Hot', 'High', 'False'),
 ('Rain', 'Mild', 'High', 'False'),
 ('Rain', 'Cool', 'Normal', 'False'),
 ('Rain', 'Cool', 'Normal', 'True'),
 ('Overcast', 'Cool', 'Normal', 'True'),
 ('Sunny', 'Mild', 'High', 'False'),
 ('Sunny', 'Cool', 'Normal', 'False'),
 ('Rain', 'Mild', 'Normal', 'False'),
 ('Sunny', 'Mild', 'Normal', 'True'),
 ('Overcast', 'Mild', 'High', 'True'),
 ('Overcast', 'Hot', 'Normal', 'False'),
 ('Rain', 'Mild', 'High', 'True')]

In [9]:
df=pd.DataFrame(zipdata,columns=['outlook','temp','humidity','windy'])
df

     outlook  temp humidity  windy
0      Sunny   Hot     High  False
1      Sunny   Hot     High   True
2   Overcast   Hot     High  False
3       Rain  Mild     High  False
4       Rain  Cool   Normal  False
5       Rain  Cool   Normal   True
6   Overcast  Cool   Normal   True
7      Sunny  Mild     High  False
8      Sunny  Cool   Normal  False
9       Rain  Mild   Normal  False
10     Sunny  Mild   Normal   True
11  Overcast  Mild     High   True
12  Overcast   Hot   Normal  False
13      Rain  Mild     High   True

In [23]:
s=np.array(play)
s

array(['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'Yes', 'Yes', 'Yes', 'No'], dtype='<U3')

In [20]:
le=LabelEncoder()
df_encoded=df.apply(le.fit_transform)
df_encoded

    outlook  temp  humidity  windy
0         2     1         0      0
1         2     1         0      1
2         0     1         0      0
3         1     2         0      0
4         1     0         1      0
5         1     0         1      1
6         0     0         1      1
7         2     2         0      0
8         2     0         1      0
9         1     2         1      0
10        2     2         1      1
11        0     2         0      1
12        0     1         1      0
13        1     2         0      1

In [24]:
x=df_encoded.values
y=np.array(play)

In [25]:
model=MultinomialNB()
model.fit(x,y)
pred=model.predict([[2,0,0,0]])
pred

array(['No'], dtype='<U3')