In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r'/content/missing_data1.csv')

In [2]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       120     479.0
2         60  '2020/12/03'    103       120     340.0
3         45  '2020/12/04'    109       120     282.4
4         45  '2020/12/05'    117       120     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       120     374.0
7        450  '2020/12/08'    104       120     253.3
8         30  '2020/12/09'    109       120     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       120     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       120     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       120     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       120     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       120       NaN
29        60  '2020/12/29'    100       120     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [3]:
df['Duration']=df['Duration'].replace(450,55)

In [4]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       120     479.0
2         60  '2020/12/03'    103       120     340.0
3         45  '2020/12/04'    109       120     282.4
4         45  '2020/12/05'    117       120     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       120     374.0
7         55  '2020/12/08'    104       120     253.3
8         30  '2020/12/09'    109       120     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       120     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       120     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       120     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       120     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       120       NaN
29        60  '2020/12/29'    100       120     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [9]:
df['Date']=df['Date'].replace('20201226',"'2020/12/26'")

In [35]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       120     479.0
2         60  '2020/12/03'    103       120     340.0
3         45  '2020/12/04'    109       120     282.4
4         45  '2020/12/05'    117       120     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       120     374.0
7         55  '2020/12/08'    104       120     253.3
8         30  '2020/12/09'    109       120     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       120     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       120     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       120     364.2
22        45      7.651515    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       120     246.0
25        60  '2020/12/25'    102       126     334.5
26        60  '2020/12/26'    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       120       NaN
29        60  '2020/12/29'    100       120     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [38]:
df['Date']=df['Date'].replace('7.651515','2020/12/22')
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       120     479.0
2         60  '2020/12/03'    103       120     340.0
3         45  '2020/12/04'    109       120     282.4
4         45  '2020/12/05'    117       120     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       120     374.0
7         55  '2020/12/08'    104       120     253.3
8         30  '2020/12/09'    109       120     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       120     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       120     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       120     364.2
22        45      7.651515    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       120     246.0
25        60  '2020/12/25'    102       126     334.5
26        60  '2020/12/26'    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       120       NaN
29        60  '2020/12/29'    100       120     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [43]:
df['Date']=pd.to_datetime(df['Date'],yearfirst=True,format='%y%m%d')

In [44]:
df

    Duration                          Date  Pulse  Maxpulse  Calories
0         60 2020-12-01 00:00:00.000000000    110       130     409.1
1         60 2020-12-02 00:00:00.000000000    117       120     479.0
2         60 2020-12-03 00:00:00.000000000    103       120     340.0
3         45 2020-12-04 00:00:00.000000000    109       120     282.4
4         45 2020-12-05 00:00:00.000000000    117       120     406.0
5         60 2020-12-06 00:00:00.000000000    102       127     300.0
6         60 2020-12-07 00:00:00.000000000    110       120     374.0
7         55 2020-12-08 00:00:00.000000000    104       120     253.3
8         30 2020-12-09 00:00:00.000000000    109       120     195.1
9         60 2020-12-10 00:00:00.000000000     98       124     269.0
10        60 2020-12-11 00:00:00.000000000    103       120     329.3
11        60 2020-12-12 00:00:00.000000000    100       120     250.7
12        60 2020-12-12 00:00:00.000000000    100       120     250.7
13        60 2020-12-13 00:00:00.000000000    106       128     345.3
14        60 2020-12-14 00:00:00.000000000    104       120     379.3
15        60 2020-12-15 00:00:00.000000000     98       123     275.0
16        60 2020-12-16 00:00:00.000000000     98       120     215.2
17        60 2020-12-17 00:00:00.000000000    100       120     300.0
18        45 2020-12-18 00:00:00.000000000     90       112       NaN
19        60 2020-12-19 00:00:00.000000000    103       123     323.0
20        45 2020-12-20 00:00:00.000000000     97       125     243.0
21        60 2020-12-21 00:00:00.000000000    108       120     364.2
22        45 1970-01-01 00:00:00.000000007    100       119     282.0
23        60 2020-12-23 00:00:00.000000000    130       101     300.0
24        45 2020-12-24 00:00:00.000000000    105       120     246.0
25        60 2020-12-25 00:00:00.000000000    102       126     334.5
26        60 2020-12-26 00:00:00.000000000    100       120     250.0
27        60 2020-12-27 00:00:00.000000000     92       118     241.0
28        60 2020-12-28 00:00:00.000000000    103       120       NaN
29        60 2020-12-29 00:00:00.000000000    100       120     280.0
30        60 2020-12-30 00:00:00.000000000    102       129     380.3
31        60 2020-12-31 00:00:00.000000000     92       115     243.0

In [45]:
df.isna().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [46]:
df['Calories']=df['Calories'].fillna(df['Calories'].mean())

In [47]:
df

    Duration                          Date  Pulse  Maxpulse  Calories
0         60 2020-12-01 00:00:00.000000000    110       130    409.10
1         60 2020-12-02 00:00:00.000000000    117       120    479.00
2         60 2020-12-03 00:00:00.000000000    103       120    340.00
3         45 2020-12-04 00:00:00.000000000    109       120    282.40
4         45 2020-12-05 00:00:00.000000000    117       120    406.00
5         60 2020-12-06 00:00:00.000000000    102       127    300.00
6         60 2020-12-07 00:00:00.000000000    110       120    374.00
7         55 2020-12-08 00:00:00.000000000    104       120    253.30
8         30 2020-12-09 00:00:00.000000000    109       120    195.10
9         60 2020-12-10 00:00:00.000000000     98       124    269.00
10        60 2020-12-11 00:00:00.000000000    103       120    329.30
11        60 2020-12-12 00:00:00.000000000    100       120    250.70
12        60 2020-12-12 00:00:00.000000000    100       120    250.70
13        60 2020-12-13 00:00:00.000000000    106       128    345.30
14        60 2020-12-14 00:00:00.000000000    104       120    379.30
15        60 2020-12-15 00:00:00.000000000     98       123    275.00
16        60 2020-12-16 00:00:00.000000000     98       120    215.20
17        60 2020-12-17 00:00:00.000000000    100       120    300.00
18        45 2020-12-18 00:00:00.000000000     90       112    304.68
19        60 2020-12-19 00:00:00.000000000    103       123    323.00
20        45 2020-12-20 00:00:00.000000000     97       125    243.00
21        60 2020-12-21 00:00:00.000000000    108       120    364.20
22        45 1970-01-01 00:00:00.000000007    100       119    282.00
23        60 2020-12-23 00:00:00.000000000    130       101    300.00
24        45 2020-12-24 00:00:00.000000000    105       120    246.00
25        60 2020-12-25 00:00:00.000000000    102       126    334.50
26        60 2020-12-26 00:00:00.000000000    100       120    250.00
27        60 2020-12-27 00:00:00.000000000     92       118    241.00
28        60 2020-12-28 00:00:00.000000000    103       120    304.68
29        60 2020-12-29 00:00:00.000000000    100       120    280.00
30        60 2020-12-30 00:00:00.000000000    102       129    380.30
31        60 2020-12-31 00:00:00.000000000     92       115    243.00

In [48]:
df.isna().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [50]:
df['Date'] = pd.to_datetime(df['Date']).dt.date

In [51]:
df

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020-12-01    110       130    409.10
1         60  2020-12-02    117       120    479.00
2         60  2020-12-03    103       120    340.00
3         45  2020-12-04    109       120    282.40
4         45  2020-12-05    117       120    406.00
5         60  2020-12-06    102       127    300.00
6         60  2020-12-07    110       120    374.00
7         55  2020-12-08    104       120    253.30
8         30  2020-12-09    109       120    195.10
9         60  2020-12-10     98       124    269.00
10        60  2020-12-11    103       120    329.30
11        60  2020-12-12    100       120    250.70
12        60  2020-12-12    100       120    250.70
13        60  2020-12-13    106       128    345.30
14        60  2020-12-14    104       120    379.30
15        60  2020-12-15     98       123    275.00
16        60  2020-12-16     98       120    215.20
17        60  2020-12-17    100       120    300.00
18        45  2020-12-18     90       112    304.68
19        60  2020-12-19    103       123    323.00
20        45  2020-12-20     97       125    243.00
21        60  2020-12-21    108       120    364.20
22        45  1970-01-01    100       119    282.00
23        60  2020-12-23    130       101    300.00
24        45  2020-12-24    105       120    246.00
25        60  2020-12-25    102       126    334.50
26        60  2020-12-26    100       120    250.00
27        60  2020-12-27     92       118    241.00
28        60  2020-12-28    103       120    304.68
29        60  2020-12-29    100       120    280.00
30        60  2020-12-30    102       129    380.30
31        60  2020-12-31     92       115    243.00

In [53]:
df.iloc[22,df['Date']]=

In [54]:
df

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020-12-01    110       130    409.10
1         60  2020-12-02    117       120    479.00
2         60  2020-12-03    103       120    340.00
3         45  2020-12-04    109       120    282.40
4         45  2020-12-05    117       120    406.00
5         60  2020-12-06    102       127    300.00
6         60  2020-12-07    110       120    374.00
7         55  2020-12-08    104       120    253.30
8         30  2020-12-09    109       120    195.10
9         60  2020-12-10     98       124    269.00
10        60  2020-12-11    103       120    329.30
11        60  2020-12-12    100       120    250.70
12        60  2020-12-12    100       120    250.70
13        60  2020-12-13    106       128    345.30
14        60  2020-12-14    104       120    379.30
15        60  2020-12-15     98       123    275.00
16        60  2020-12-16     98       120    215.20
17        60  2020-12-17    100       120    300.00
18        45  2020-12-18     90       112    304.68
19        60  2020-12-19    103       123    323.00
20        45  2020-12-20     97       125    243.00
21        60  2020-12-21    108       120    364.20
22        45  1970-01-01    100       119    282.00
23        60  2020-12-23    130       101    300.00
24        45  2020-12-24    105       120    246.00
25        60  2020-12-25    102       126    334.50
26        60  2020-12-26    100       120    250.00
27        60  2020-12-27     92       118    241.00
28        60  2020-12-28    103       120    304.68
29        60  2020-12-29    100       120    280.00
30        60  2020-12-30    102       129    380.30
31        60  2020-12-31     92       115    243.00